In [1]:
import numpy as np
import pandas as pd

№ 1.3.1.
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами

In [2]:
matrix = np.matrix(np.zeros((8, 8), dtype=int))
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
matrix

matrix([[1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1]])

№ 1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arange.

In [3]:
matrix = np.matrix([np.arange(0, 5) for _ in range(5)])
matrix

matrix([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

№ 1.3.3
Создать массив 3x3x3 со случайными значениями.

In [4]:
arr = np.random.randint(100, size=27).reshape(3, 3, 3)
arr

array([[[68, 54, 49],
        [82, 15, 42],
        [45, 46, 65]],

       [[44, 73, 57],
        [40, 91, 94],
        [48, 88, 17]],

       [[57, 98, 12],
        [44, 69,  2],
        [31, 67, 39]]])

№ 1.3.4
Создать матрицу с 0 внутри, и 1 на границах.

In [5]:
n = 10
matrix = np.matrix(np.zeros((5, 5), dtype=int))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
matrix

matrix([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]])

№ 1.3.5
Создайте массив и отсортируйте его по убыванию.

In [6]:
arr = np.random.uniform(high=100, size=10)
arr.sort()
print(arr)

[29.7177723  31.50108894 32.57769568 37.42312934 49.25524575 50.64629934
 57.05740667 69.37180135 81.40682381 93.94056271]


№ 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность.

In [7]:
matrix = np.matrix(np.random.rand(10, 10))
print(f'Форма: {matrix.shape}, '
      f'Размер: {matrix.size}, '
      f'Размерность: {matrix.ndim}')

Форма: (10, 10), Размер: 100, Размерность: 2


№ 2.3.1
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [8]:
point1 = pd.Series([4, 4, 4])
point2 = pd.Series([10, 10, 10])
print(f'Евклидово расстояние от (4, 4, 4) до (10, 10, 10):'
      f' {round((sum((point1 - point2) ** 2)) ** 0.5, 2)}')

Евклидово расстояние от (4, 4, 4) до (10, 10, 10): 10.39


№ 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [9]:
url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"
data = pd.read_csv(url)

№2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

№2.2.5
Проанализировать характеристики фрейма данных.

In [10]:
data.head(5)

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [11]:
data.tail(5)

year   name gender  count
624231  2018  Zylas      M      5
624232  2018  Zyran      M      5
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [12]:
data.year.describe() # Описание столбца year

count    624236.000000
mean       2009.115961
std           5.383550
min        2000.000000
25%        2005.000000
50%        2009.000000
75%        2014.000000
max        2018.000000
Name: year, dtype: float64

In [13]:
data.name.describe() # Описание столбца с именами

count     624236
unique     68265
top        Emily
freq          38
Name: name, dtype: object

№ 2.2.6
Выберите индивидуальные данные или срезы фрейма данных.

In [14]:
data.iloc[0:4, 1] # Срез первых 4-х имен

0      Emily
1     Hannah
2    Madison
3     Ashley
Name: name, dtype: object

№2.2.7
Требуется отобрать строки фрейма данных на основе некоторого
условия.

In [15]:
# Условие - мужские имена, родившихся в 2016 году
masks = [data['year'] == 2016, data['gender'] == 'M']
male_names_2016 = data[masks[0] & masks[1]]
male_names_2016.head(5)

year     name gender  count
545439  2016     Noah      M  19117
545440  2016     Liam      M  18218
545441  2016  William      M  15761
545442  2016    Mason      M  15244
545443  2016    James      M  14862

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [16]:
from sklearn import preprocessing
data = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
data.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [17]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data[["sepal_length_cm"]] = min_max_scaler.fit_transform(data[["sepal_length_cm"]])
std_scaler = preprocessing.StandardScaler()
data[["sepal_width_cm"]] = std_scaler.fit_transform(data[["sepal_width_cm"]])
data

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]